<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_enter_at_inspire_banner</name>
   <tag></tag>
   <elementGuidId>776b522f-bc9a-484e-a598-dcc40571e83b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[7]/div/div/div/div/div/div[2]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > div > a.pagebuilder-button-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Enter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a5ac099-7683-4969-83f4-5559ca152f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pagebuilder-button-link</value>
      <webElementGuid>3b20c1b0-2b01-4ca0-b655-afe0a4bd1e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link-type</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>84b92174-919b-4bd7-84dd-a0488ca335a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-element</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>abe84d0c-576a-4d5f-a2b7-669509c7b70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>67fd983f-4cb1-4e3d-8eb6-96a0651c07fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[7]/div[1]/div[@class=&quot;widget block block-static-block&quot;]/div[@class=&quot;curio-portal-banner&quot;]/div[@class=&quot;pagebuilder-column-group&quot;]/div[@class=&quot;pagebuilder-column&quot;]/div[2]/div[1]/a[@class=&quot;pagebuilder-button-link&quot;]</value>
      <webElementGuid>91eeb74c-72b8-42af-85a8-bfb67a33129a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[7]/div/div/div/div/div/div[2]/div/a</value>
      <webElementGuid>802b9dd0-9a4a-4e8c-9aa6-ebaea8e2d579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyNTT2 Test 393 video inspire home. dep nhat'])[2]/following::a[1]</value>
      <webElementGuid>d5bc69f4-b055-4361-9b4c-b96472d6b617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Padlock'])[1]/following::a[2]</value>
      <webElementGuid>3864c115-3662-4618-91da-00e0eb857524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pick of the week'])[1]/preceding::a[1]</value>
      <webElementGuid>51fa9f59-0bc2-4b0f-b064-a92737a8aa78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[438]</value>
      <webElementGuid>458fc8db-95eb-419e-ac55-456d906adab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/div/div[2]/div/a</value>
      <webElementGuid>7399cfb8-27fe-4618-9a9a-ea0c06e4ce6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Enter' or . = 'Enter')]</value>
      <webElementGuid>362908ac-b4c3-4b82-b880-45809adb3e5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
