<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_inspire_home_logo</name>
   <tag></tag>
   <elementGuidId>bd3fdf84-d7ad-4ba5-9a32-c0fa4068b852</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='O3KSFV4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#O3KSFV4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Curio Home&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c6ab0133-a760-40aa-9550-c7107d30b5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>O3KSFV4</value>
      <webElementGuid>15ed75d2-4cf6-4b55-8576-e80549cca911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mcdev.ubteam.com/media/wysiwyg/InspireHome_Log.png</value>
      <webElementGuid>53878487-a469-4efe-97f7-a90907e89a74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Inspire Home</value>
      <webElementGuid>ba367930-b2e5-41e6-8c4e-0476fe8ab193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>a41f7c6f-27ab-47bf-8a64-338a8873d7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>34</value>
      <webElementGuid>566ed4f6-926c-4a32-8559-94f2e0f0f242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;O3KSFV4&quot;)</value>
      <webElementGuid>0e2fa2db-fabe-44ed-84bf-a61274333c17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='O3KSFV4']</value>
      <webElementGuid>294f2f0a-c3ef-4cd1-9228-90e910198dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='html-body']/div[3]/div/div/div/div/div/div/div/div/p/a/img</value>
      <webElementGuid>0a08b0d1-6798-4d7a-b03e-fa31d14ab8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Inspire Home'])[2]</value>
      <webElementGuid>cf2c82c9-1d23-4abb-9c93-72e55a4c5ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/p/a/img</value>
      <webElementGuid>22de6342-476b-470c-b330-8de06bcc196f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'O3KSFV4' and @src = 'https://mcdev.ubteam.com/media/wysiwyg/InspireHome_Log.png' and @alt = 'Inspire Home']</value>
      <webElementGuid>e5764924-ba1e-4a3c-8a29-9f0dc58de463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
