<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Video libraryDownloadsBlogFavouritesMy v_003ee8</name>
   <tag></tag>
   <elementGuidId>8ef6e111-5ae8-4261-9ab4-91eff76adb95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='nav-curio-home-menu-172500729066d185ba70f4a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-curio-home-menu-172500729066d185ba70f4a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>header >> internal:has-text=&quot;Toggle Nav Video libraryDownloadsBlogFavouritesMy videosInspire vision Search In&quot;i >> internal:role=list</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>e31ca3d2-55d9-4afb-8095-2333c712b4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-curio-home-menu-172500729066d185ba70f4a</value>
      <webElementGuid>f115beee-ff78-4bc0-a1cc-100fa7505a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-curio-home-menu-172500729066d185ba70f4a</value>
      <webElementGuid>9bb52d83-d240-458f-b77b-1d19ad957323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle-mobile-nav</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>faba0a16-b37d-49fa-b883-3f950ea001c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Video libraryDownloadsBlogFavouritesMy videosInspire vision</value>
      <webElementGuid>953c4834-67bc-427d-b8d5-2078f8240f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;html-body&quot;)/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;page-header-top&quot;]/div[@class=&quot;header content&quot;]/div[@class=&quot;curio-home-navigation-new background-image-menu&quot;]/div[@class=&quot;row-full-width-inner&quot;]/div[@class=&quot;pagebuilder-column-group&quot;]/div[@class=&quot;pagebuilder-column obc-navigation-menu&quot;]/div[1]/div[@id=&quot;curio-home-menu-1725007290&quot;]/div[@class=&quot;navigation navitaion172500729066d185ba70f4a&quot;]/ul[@id=&quot;nav-curio-home-menu-172500729066d185ba70f4a&quot;]</value>
      <webElementGuid>bcd069f3-5cd1-41c3-b923-9493cba58247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='nav-curio-home-menu-172500729066d185ba70f4a']</value>
      <webElementGuid>013230c7-c605-4fd6-afb2-9dbc0be15573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='curio-home-menu-1725007290']/div[3]/ul</value>
      <webElementGuid>b0129c66-5ead-404a-a071-f564c15aaabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Nav'])[4]/following::ul[1]</value>
      <webElementGuid>0120aa05-dca3-42f3-a6d3-29d865e66f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[3]/following::ul[1]</value>
      <webElementGuid>f159a39c-1168-46df-b029-fd98608460ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul</value>
      <webElementGuid>f147d1e0-086f-4d00-9e0e-dd48de9aba7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'nav-curio-home-menu-172500729066d185ba70f4a' and (text() = 'Video libraryDownloadsBlogFavouritesMy videosInspire vision' or . = 'Video libraryDownloadsBlogFavouritesMy videosInspire vision')]</value>
      <webElementGuid>c0aa30f6-160f-4840-89d7-b92bd3cdbf81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
