<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filter by</name>
   <tag></tag>
   <elementGuidId>0e02060d-ed30-40e2-92ec-654b7d5ad052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='library_obc_filter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#library_obc_filter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Filter by Category 1401 Curio Same Category(3) Administration Administration Adm&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb5fe39b-69d4-421f-a3ef-84b66471114d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-filter</value>
      <webElementGuid>e87b601a-87fc-4b49-90aa-361c026f8898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>library_obc_filter</value>
      <webElementGuid>b2cf8fa6-2054-4533-a6d4-a2a045cd33e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>scope:'library-obc-filter'</value>
      <webElementGuid>e22489d8-ce67-48e8-83cd-5b084a2db029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter by  Category 1401 Curio Same Category(3) Administration Administration Administration(3)  Business Toolkit(2) Cat &amp; Dog(2) Curio Vision Long name MyNTT2 Curio Vision Long na(1) Customer Service(1) Household Portal(7) LinkedIn Learning(7) None Category(94) OBC Portal(54) Other Category(1) Test(1) testvp(1) vinh test 1255(2)  See more Series 246-p6 series 01(1) 2677 02(1) MyNTT2 Series Home 1(3) MyNTT2 Series Home 2(2) MyNTT2 Series Home 3(1) None(170) This is series(1)  See more</value>
      <webElementGuid>7a0839bd-d670-48f3-b03b-dfe918f32912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;library_obc_filter&quot;)</value>
      <webElementGuid>0c020b2b-f119-47cb-a537-8ecb18506e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='library_obc_filter']</value>
      <webElementGuid>1493633d-ee58-4518-a5eb-547c709c81fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[5]/div/div/div/div/div</value>
      <webElementGuid>99c4349c-733a-4767-abf2-de05ec1c19b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='click here now'])[1]/following::div[6]</value>
      <webElementGuid>a991c27e-05ef-4082-adff-4135810253c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='new3'])[1]/following::div[6]</value>
      <webElementGuid>9a9d95ad-6e5d-46b2-a177-e118971a4792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/div/div/div/div/div</value>
      <webElementGuid>7c2f059e-846e-453d-b6de-ddf6de5258fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'library_obc_filter' and (text() = 'Filter by  Category 1401 Curio Same Category(3) Administration Administration Administration(3)  Business Toolkit(2) Cat &amp; Dog(2) Curio Vision Long name MyNTT2 Curio Vision Long na(1) Customer Service(1) Household Portal(7) LinkedIn Learning(7) None Category(94) OBC Portal(54) Other Category(1) Test(1) testvp(1) vinh test 1255(2)  See more Series 246-p6 series 01(1) 2677 02(1) MyNTT2 Series Home 1(3) MyNTT2 Series Home 2(2) MyNTT2 Series Home 3(1) None(170) This is series(1)  See more' or . = 'Filter by  Category 1401 Curio Same Category(3) Administration Administration Administration(3)  Business Toolkit(2) Cat &amp; Dog(2) Curio Vision Long name MyNTT2 Curio Vision Long na(1) Customer Service(1) Household Portal(7) LinkedIn Learning(7) None Category(94) OBC Portal(54) Other Category(1) Test(1) testvp(1) vinh test 1255(2)  See more Series 246-p6 series 01(1) 2677 02(1) MyNTT2 Series Home 1(3) MyNTT2 Series Home 2(2) MyNTT2 Series Home 3(1) None(170) This is series(1)  See more')]</value>
      <webElementGuid>1b2c06b7-333a-4755-a0fd-a488cdc1ac94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
