<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pick of the week</name>
   <tag></tag>
   <elementGuidId>c122be7b-c1db-439d-bb5f-d29c02d6e327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[8]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pick-of-the-week.curio-home</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.pick-of-the-week</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3bedf61-cc8e-4c3f-94c1-89365cbaff1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pick-of-the-week curio-home</value>
      <webElementGuid>6dd90c4c-1035-481a-b4a2-89f2dac692ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pick of the week MyNTT2 Dynamic message Test In Customer Service Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus in dui erat. Maecenas non mollis enim. Donec vulputate eu libero non sodales. Sed sed ultricies nisl, vel lobortis or See all here myntt2</value>
      <webElementGuid>d5d248e2-373d-405e-9d92-7ee8ab56a38b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[8]/div[1]/div[@class=&quot;widget block block-static-block&quot;]/div[1]/div[1]/div[@class=&quot;pick-of-the-week curio-home&quot;]</value>
      <webElementGuid>48dae527-9df0-4d01-a78a-c5f22cb1de22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[8]/div/div/div/div/div</value>
      <webElementGuid>91664197-1854-4d59-ac0e-c8e0341e298e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter'])[1]/following::div[6]</value>
      <webElementGuid>5ab6cc61-1b7c-4002-a166-22281f6e6d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyNTT2 Test 393 video inspire home. dep nhat'])[2]/following::div[16]</value>
      <webElementGuid>32ad1a8e-55b4-4e8a-a301-48893b1ca169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div</value>
      <webElementGuid>0b62006a-7ed0-4deb-aa8d-5e9620fee505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pick of the week MyNTT2 Dynamic message Test In Customer Service Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus in dui erat. Maecenas non mollis enim. Donec vulputate eu libero non sodales. Sed sed ultricies nisl, vel lobortis or See all here myntt2' or . = 'Pick of the week MyNTT2 Dynamic message Test In Customer Service Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus in dui erat. Maecenas non mollis enim. Donec vulputate eu libero non sodales. Sed sed ultricies nisl, vel lobortis or See all here myntt2')]</value>
      <webElementGuid>91246492-cb7d-4ea0-a955-52cf83bdb780</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
