<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_inspire_home_logo (1)</name>
   <tag></tag>
   <elementGuidId>d14e2b69-eb56-4f49-9f11-abbdef9a8579</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='html-body']/div[3]/header[2]/div/div/div/div/div/div/p/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p > a > img.lazy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Inspire Home&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>33d45be4-0e9f-47f0-b842-ca37213dbbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>5e9d3891-bb60-428c-9348-82f78f34a368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>4c7e7df4-c5ca-4bb4-9155-34bcc30ccfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>eec671a4-2137-42ef-a6c8-02eb0bee50d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mcdev.ubteam.co.uk/static/version1724985741/frontend/Magento/base/default/Ubt_Olp/images/InspireHome_Logo.png</value>
      <webElementGuid>d8c0d8ea-cbe8-4308-bcf9-4c4846953ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Inspire Home</value>
      <webElementGuid>c36c513f-d9bc-41e5-84e3-6043c513ab79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>160</value>
      <webElementGuid>7b46bd93-9c0d-4bfb-bc68-b7cae797c8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e5c0babf-29ca-4b95-ad7e-e1f53e0a3131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;html-body&quot;)/div[@class=&quot;page-wrapper&quot;]/header[@class=&quot;page-header-top&quot;]/div[@class=&quot;header content&quot;]/div[@class=&quot;curio-home-navigation-new background-image-menu&quot;]/div[@class=&quot;row-full-width-inner&quot;]/div[@class=&quot;pagebuilder-column-group&quot;]/div[@class=&quot;pagebuilder-column obc-navigation-logo&quot;]/div[1]/p[1]/a[1]/img[@class=&quot;lazy&quot;]</value>
      <webElementGuid>142ba778-8aa3-4b56-9444-2d63ac688b39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='html-body']/div[3]/header[2]/div/div/div/div/div/div/p/a/img</value>
      <webElementGuid>336f3f87-0b0f-4a82-a17c-9da301289acd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Inspire Home']</value>
      <webElementGuid>2e1ca942-8293-46d4-99e1-c4539cfa34dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a/img</value>
      <webElementGuid>a0a17a31-2768-4d73-90b7-5c0c11fcb8d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://mcdev.ubteam.co.uk/static/version1724985741/frontend/Magento/base/default/Ubt_Olp/images/InspireHome_Logo.png' and @alt = 'Inspire Home']</value>
      <webElementGuid>c5f9f870-edb8-43b1-b9b1-2a389c29bf03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
