<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Pick of the week</name>
   <tag></tag>
   <elementGuidId>db507449-bcbb-4dc4-808c-4d79a882bede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div[8]/div/div/div/div/div/div/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4.widget-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Pick of the week&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>f926b973-2939-4020-96b8-8702a2ca94af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widget-title</value>
      <webElementGuid>3e3aeb61-b37d-436d-b5be-6bfcd2a00ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pick of the week</value>
      <webElementGuid>ee96fd1c-10e8-4843-82a6-98fd4cceecbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[8]/div[1]/div[@class=&quot;widget block block-static-block&quot;]/div[1]/div[1]/div[@class=&quot;pick-of-the-week curio-home&quot;]/div[1]/div[@class=&quot;row-full-width-inner&quot;]/h4[@class=&quot;widget-title&quot;]</value>
      <webElementGuid>6116f6d5-d789-4e32-8775-df6288378409</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[8]/div/div/div/div/div/div/div/h4</value>
      <webElementGuid>b8f30f07-0a95-46e7-b5d0-69bcacc6910b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter'])[1]/following::h4[1]</value>
      <webElementGuid>057a9f36-fa20-4704-b972-05fac75162ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyNTT2 Test 393 video inspire home. dep nhat'])[2]/following::h4[1]</value>
      <webElementGuid>01120403-2c41-4b78-85ef-1484999f2109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MyNTT2 Dynamic message Test'])[1]/preceding::h4[1]</value>
      <webElementGuid>8c8ef7d6-0849-44dd-b73d-6952aa47a330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pick of the week']/parent::*</value>
      <webElementGuid>16fb2952-34b7-4691-8310-0c99bc961587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>29ae8d17-ef24-49cd-ba26-f688985e6744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Pick of the week' or . = 'Pick of the week')]</value>
      <webElementGuid>aad524be-19bf-44e7-a397-f8cf7212d394</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
